// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  earlyAccess: true,
  schema: 'prisma/schema.prisma',
  migrate: {
    adapter(env) {
      return new PrismaPg({ connectionString: env.DATABASE_URL });
    },
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
  // migrations: {
  //   path: 'prisma/migrations',
  // },
});
